gnustep/tools-make

- ChangeLog
- GNUmakefile.in
- Master/source-distribution.make
This adds support for git-tag and git-dist of both gnustep-make and other tools that may be using it. Can you please take a look and assess whether there's any glaring issue?
I'll be using this to cut the -gui release soon.
> Support creating a Git tag and exporting tarball from the tag.

- target.make
With Runtime 2.0, the text next to classes as discovered by this nm command changed.
This prevented NSBundles from being loaded from their location.
This pull request addresses those changes for Linux. With this solution, ProjectCenter is able to correctly load bundles when built under Runtime 2.0, and the LogPanel shows up during startup.
Without this change, ProjectCenter cannot load its bundles, and the LogPanel does not appear.
> Fix extract class names for runtime 2.0 (Linux only)

- target.make
This is an attempt to apply the fix that works under Linux for GNUstep Runtime > 2.0 to other operating systems (Darwin, OpenBSD, Mingw32/64).
Needs to be tested for each of those platforms.
> Fix extract class names for runtime2.0 (all OSes)

- ANNOUNCE
- ChangeLog
- Documentation/announce.texi
- Documentation/news.texi
While preparing the email, I noticed the ANNOUNCE file for `-make` doesn't mention the GPG key, and there are other subtle differences.
I'm creating this pull request across `make`, `base`, `gui` and `back`.
n.b.: `make` is a special case because it doesn't mention `GNUSTEP-MAKE-FTP-MACHINE` and I don't see a point in introducing that.
> Normalize annoucement file between core libraries

- ChangeLog
- configure
- m4/gs_gcc_version.m4
extraction. Versions of gcc > 7.0 require this parameter to output
the full version number. Older versions should just ignore this option.
* configure: Regenerate. This remove the runstatedir option as my version
of autoconfig does not include it.
> * gs_gcc_version.m4: Add -dumpfullversion to the version

- Instance/application.make
Support for storyboards in GNUmakefiles.   This change simply adds the change to generate the entry in the Info.plist for loading a storyboard when one is specified.
> Support for storyboards in GNUmakefiles.

- ChangeLog
- configure
- configure.ac
Configure currently always forcefully disables support for native exceptions on Windows, even though they should be supported when using Clang and the ng runtime.
With this change, the check is only forcefully disabled when using the gnu runtime.
> Enable native Objective-C exception check on Windows

- ChangeLog
- configure
- m4/gs_objc_runtime.m4
This is the library file name used by libobjc2 on Windows. Fixes having to manually specify library and header search paths.
> Check for objc.dll to support libobjc2 on Windows.

- configure
- m4/gs_objc_runtime.m4
objc.lib is what is used for linking. Matches changes in https://github.com/gnustep/libs-base/pull/165.
> Check for objc.lib instead of objc.dll

- ChangeLog
- Instance/library.make
- Instance/rules.make
- Instance/subproject.make
- common.make
- configure
- m4/gs_cc_is_clang.m4
- target.make
These changes enable building on Windows with Clang, libobjc2, and the MSVC ABI (i.e. not using MinGW).
Requires using a standard Windows Clang build that e.g. comes with Visual Studio or is available as pre-built binary from the [LLVM website](https://releases.llvm.org/download.html). Invoking `clang -v` should show a target like `x86_64-pc-windows-msvc`.
Configure must be invoked with a host like `x86_64-pc-windows` or `i386-pc-windows`, e.g.:
```
export CC=/C/LLVM/bin/clang
export CXX=/C/LLVM/bin/clang++
export OBJCXX=/C/LLVM/bin/clang++
./configure --host=x86_64-pc-windows --with-library-combo=ng-gnu-gnu --with-runtime-abi=gnustep-2.0 --prefix=/c/GNUstep/x64 LDFLAGS="-fuse-ld=lld"
```
As the Windows linker does not support incremental linking using `ld -r`, this also contains a change …
> Support building on Windows with Clang MSVC target

- ChangeLog
- TestFramework/Testing.h
- configure
- configure.ac
- target.make
A couple of fixes for Windows MSVC:
- Link against debug or release UCRT DLLs depending on $debug
- Removed unused `-pthread` flag (caused compiler warning)
- Fix CFLAGS, as AC_PROG_CC will not detect Clang in MSVC mode as a GNU C compiler and therefore sets CFLAGS to just `-g`.
- Fixes incorrect import statement in Testing.h, which caused linker errors when running tests on Windows MSVC because the compiler needs to see the __dllspec on NSCalendarDate in order to be able to link against it.
> Windows MSVC fixes

- ChangeLog
- TestFramework/Testing.h
Fixes failing tests that don't contain any Objective-C constructs on Windows MSVC due to this Clang bug:
https://bugs.llvm.org/show_bug.cgi?id=49681
> Add workaround for Clang bug on Windows MSVC

- target.make
Silences a bunch of warnings like the following when building for Windows MSVC, as can be seen in [recent CI runs](https://github.com/gnustep/libs-base/runs/3274204118?check_suite_focus=true). Please let me know if there’s a better place to put this.
```
In file included from GSLocale.m:25:
In file included from ././common.h:35:
../Headers\GNUstepBase/GSVersionMacros.h:222:10: warning: #include resolved using non-portable Microsoft search rules as: ././GNUstepBase/GSConfig.h [-Wmicrosoft-include]
#include "GNUstepBase/GSConfig.h"
^
```
Stack Overflow has [a bit more info](https://stackoverflow.com/a/48539191/1534401) on the warning. Silencing it seemed like the best way forward to me.
> Windows MSVC: suppress Clang warning -Wmicrosoft-include

- Documentation/GNUmakefile
* Documentation/GNUmakefile:
- all packages except for tools-make are installed
to the LOCAL domain nowadays...
it would be better to install the Documentation part
of the tools-make there too because it contains
articles/docs referenced from other libraries'
Documentation parts
(e.g. base' Documentation/HtmlNav/index.html)
> * Documentation is now installed in the LOCAL domain

- Instance/framework.make
Windows uses a PDB file to store debug information. The path of this file is computed here: https://github.com/gnustep/tools-make/blob/00a4e989aee39b50852f7e49a67b19cc311dbbe8/target.make#L982 
LIB_LINK_PDB_FILE is not populated when building a framework on Windows MSVC. LIB_LINK_PDB_FILE is defined in library.make, but missing in framework.make: https://github.com/gnustep/tools-make/blob/00a4e989aee39b50852f7e49a67b19cc311dbbe8/Instance/library.make#L239.
> Add missing LIB_LINK_PDB_FILE variable to framework.make

- TestFramework/gnustep-tests.in
- common.make
- m4/gs_check_abi20_linker.m4
- target.make
- gnustep-tests:
- Add --make-debug flag to enable make internal debug output (Stored in test.log)
- Add --make-no-silent to echo every make command (Stored in test.log)
- Add -v invocation to CC when --verbose flag is set
- target.make:
- Generate Windows MSVC PDB debug symbol files when debug is set to yes
- m4/gs_check_abi20_linker.m4:
- Fix typo
> Windows MSVC debug symbols, gnustep-tests extension, and typo fixes

- rules.make
GS_WITH_ARC is ignored on apple-apple-apple. This patch checks for the right darwin version (above 9) in rules.make and sets a flag accordingly.
> Detect ARC when using apple runtime

- configure
- m4/gs_check_abi20_linker.m4
See: #36 
Instead of just printing the path for ld, we compile a small test program with the CFLAGS and LDFLAGS from configure and increased verbosity, and grep the linker output.
Configure script was rebuild using `autoreconf -vi`.
Demonstration:
```sh
./configure --with-layout=debian \
--enable-native-objc-exceptions  \
--enable-objc-arc \
--prefix=/usr \
--with-runtime-abi=gnustep-2.0 \
--with-library-combo=ng-gnu-gnu \
LDFLAGS="-fuse-ld=lld -L/usr/lib/aarch64-linux-gnu" SHELLPROG=/bin/bash GNUMAKE=make
```
```plaintext
[...]
checking for runtime ABI... gnustep-2.0
checking which linker is being used... lld
checking whether the compiler supports native ObjC exceptions... yes
[...]
```
```sh
./configure --with-layout=debian \
--enable-native-objc-exceptions  \
--enable-objc-arc \ …
```
> Rewrite linker detection (GS_CHECK_ABI20_LINKER)

- common.make
On Windows MSVC `-gcodeview` is required in addition to `-g` in order to generate full debug symbols. This enables debugging Objective-C code with native Windows debugging tools such as Visual Studio or WinDBG (more info about CodeView support in LLVM can e.g. be found [here](https://llvm.org/devmtg/2016-11/Slides/Kleckner-CodeViewInLLVM.pdf)).
This change always adds the flag if `-g` is found in `OPTFLAG`.
> Ensure -gcodeview on Windows MSVC

- INSTALL
- configure
- configure.ac
- library-combo.make
- m4/gs_objc_runtime.m4
- m4/gs_runtime_abi.m4
This was tested on Ubuntu 23.10 (aarch64) and Windows 11 Pro.
> Bump Objective-C Runtime Version for libobjc2 and add installation instructions

- common.make
For more information on address sanitization read https://clang.llvm.org/docs/AddressSanitizer.html or https://gcc.gnu.org/onlinedocs/gcc/Instrumentation-Options.html#index-fsanitize_003daddress.
Address sanitization can be turned on with the new `asan` flag in GNUstep Make: `make asan=yes`.
The GNUstep Base library currently leaks memory upon program exit which makes analysis a bit cumbersome. We should improve on this, and encourage users of GNUstep make to use sanitization.
```
include $(GNUSTEP_MAKEFILES)/common.make
TOOL_NAME = demo
demo_OBJC_FILES = demo.m
-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/tool.make
-include GNUmakefile.postamble
```
```
#import <Foundation/Foundation.h>
int main() {
NSAutoreleasePool *arp = [NSAutoreleasePool new];
[arp drain];
return 0;
} …
```
> Initial address sanitisation support

- CODEOWNERS
Add a section for myself to take codeownership of 'automatic' deb rules.
This will document whom to talk to, possibly raise awareness, and ensure pull requests end up in the right place.
> CODEOWNERS: Add a section to take codeownership of 'automatic' deb rules.
